//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Psno { get; set; }
        public string employee_name { get; set; }
        public string email_id { get; set; }
        public string current_skills { get; set; }
        public string excepted_training { get; set; }
    }
}
